[package]
name = "object-trustfall-adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
gimli = "0.31.0"
iced-x86 = "1.21.0"
object = "0.36.2"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.121"
trustfall = "0.7.1"
