name: Build
on:
  push:
    branches:
      - "*"
  pull_request:
env:
  RUST_BACKTRACE: 1
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - stable
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.version }}
          components: rustfmt
      - uses: cargo-bins/cargo-binstall@main
      - name: tarpaulin_install
        run: cargo binstall -y cargo-tarpaulin
      - name: test
        run: cargo test
      - name: examples
        run: cargo check --examples
      - name: check formatting
        run: cargo fmt -- --check

